add geometry type
bradzacher/mysqldump pull request #52
Opened 2018-10-14 19:12 UTC by pbassut

2018-10-14 19:14 UTC, assignar-devops commented
### Build Failed!

The last (useful) 2 log lines are shown below:
[View Full Log](https://console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logEvent:group=/aws/codebuild/assignar-ci;stream=36e34bf5-446e-4fa3-98b7-1d6110efb7f1)
```
Cloning into 'mysqldump'...
fatal: reference is not a tree: a7f3ad8e63304f4f946f4a7b8b66f588e99cb696
```
<details><summary>Unfiltered log</summary>
<p>

```
[Container] 2018/10/14 19:13:59 Waiting for agent ping
[Container] 2018/10/14 19:13:59 Waiting for DOWNLOAD_SOURCE
[Container] 2018/10/14 19:13:59 Phase is DOWNLOAD_SOURCE
[Container] 2018/10/14 19:13:59 CODEBUILD_SRC_DIR=/codebuild/output/src461964318/src/github.com/assignar/ci
[Container] 2018/10/14 19:13:59 YAML location is /codebuild/output/src461964318/src/github.com/assignar/ci/buildspec.yml
[Container] 2018/10/14 19:13:59 Processing environment variables
[Container] 2018/10/14 19:13:59 Decrypting parameter store environment variables
[Container] 2018/10/14 19:13:59 Moving to directory /codebuild/output/src461964318/src/github.com/assignar/ci
[Container] 2018/10/14 19:13:59 Registering with agent
[Container] 2018/10/14 19:13:59 Phases found in YAML: 1
[Container] 2018/10/14 19:13:59  BUILD: 1 commands
[Container] 2018/10/14 19:13:59 Phase complete: DOWNLOAD_SOURCE Success: true
[Container] 2018/10/14 19:13:59 Phase context status code:  Message:
[Container] 2018/10/14 19:14:00 Entering phase INSTALL
[Container] 2018/10/14 19:14:00 Phase complete: INSTALL Success: true
[Container] 2018/10/14 19:14:00 Phase context status code:  Message:
[Container] 2018/10/14 19:14:00 Entering phase PRE_BUILD
[Container] 2018/10/14 19:14:00 Phase complete: PRE_BUILD Success: true
[Container] 2018/10/14 19:14:00 Phase context status code:  Message:
[Container] 2018/10/14 19:14:00 Entering phase BUILD
[Container] 2018/10/14 19:14:00 Running command node ./test.js
Cloning into 'mysqldump'...
fatal: reference is not a tree: a7f3ad8e63304f4f946f4a7b8b66f588e99cb696
child_process.js:644
    throw err;
    ^

Error: Command failed: git checkout a7f3ad8e63304f4f946f4a7b8b66f588e99cb696
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at execSync (/codebuild/output/src461964318/src/github.com/assignar/ci/test.js:7:18)
    at Object.<anonymous> (/codebuild/output/src461964318/src/github.com/assignar/ci/test.js:54:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

[Container] 2018/10/14 19:14:02 Command did not exit successfully node ./test.js exit status 1
[Container] 2018/10/14 19:14:02 Phase complete: BUILD Success: false
[Container] 2018/10/14 19:14:02 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: node ./test.js. Reason: exit status 1
[Container] 2018/10/14 19:14:02 Entering phase POST_BUILD
[Container] 2018/10/14 19:14:02 Phase complete: POST_BUILD Success: true
[Container] 2018/10/14 19:14:02 Phase context status code:  Message:
```

</p>
</details>

[Click here to retry the build](https://ut2fgw3cae.execute-api.ap-southeast-2.amazonaws.com/development//retry-build?repo=mysqldump&commit=a7f3ad8e63304f4f946f4a7b8b66f588e99cb696&retryToken=fd533514-c678-4ea6-bf51-278476494540)

2018-10-23 20:41 UTC, assignar-devops commented
### Build Failed!

The last (useful) 2 log lines are shown below:
[View Full Log](https://console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logEvent:group=/aws/codebuild/assignar-ci;stream=d02320b2-d183-43c6-b220-85889c57a01f)
```
Cloning into 'mysqldump'...
fatal: reference is not a tree: a4480f7b08916657e268d067178275cf6be1d5f8
```
<details><summary>Unfiltered log</summary>
<p>

```
[Container] 2018/10/23 20:40:45 Waiting for agent ping
[Container] 2018/10/23 20:40:45 Waiting for DOWNLOAD_SOURCE
[Container] 2018/10/23 20:40:45 Phase is DOWNLOAD_SOURCE
[Container] 2018/10/23 20:40:45 CODEBUILD_SRC_DIR=/codebuild/output/src240065650/src/github.com/assignar/ci
[Container] 2018/10/23 20:40:45 YAML location is /codebuild/output/src240065650/src/github.com/assignar/ci/buildspec.yml
[Container] 2018/10/23 20:40:45 Processing environment variables
[Container] 2018/10/23 20:40:45 Decrypting parameter store environment variables
[Container] 2018/10/23 20:40:45 Moving to directory /codebuild/output/src240065650/src/github.com/assignar/ci
[Container] 2018/10/23 20:40:45 Registering with agent
[Container] 2018/10/23 20:40:45 Phases found in YAML: 1
[Container] 2018/10/23 20:40:45  BUILD: 1 commands
[Container] 2018/10/23 20:40:45 Phase complete: DOWNLOAD_SOURCE Success: true
[Container] 2018/10/23 20:40:45 Phase context status code:  Message:
[Container] 2018/10/23 20:40:45 Entering phase INSTALL
[Container] 2018/10/23 20:40:45 Phase complete: INSTALL Success: true
[Container] 2018/10/23 20:40:45 Phase context status code:  Message:
[Container] 2018/10/23 20:40:46 Entering phase PRE_BUILD
[Container] 2018/10/23 20:40:46 Phase complete: PRE_BUILD Success: true
[Container] 2018/10/23 20:40:46 Phase context status code:  Message:
[Container] 2018/10/23 20:40:46 Entering phase BUILD
[Container] 2018/10/23 20:40:46 Running command node ./test.js
Cloning into 'mysqldump'...
fatal: reference is not a tree: a4480f7b08916657e268d067178275cf6be1d5f8
child_process.js:644
    throw err;
    ^

Error: Command failed: git checkout a4480f7b08916657e268d067178275cf6be1d5f8
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at execSync (/codebuild/output/src240065650/src/github.com/assignar/ci/test.js:7:18)
    at Object.<anonymous> (/codebuild/output/src240065650/src/github.com/assignar/ci/test.js:54:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

[Container] 2018/10/23 20:40:48 Command did not exit successfully node ./test.js exit status 1
[Container] 2018/10/23 20:40:48 Phase complete: BUILD Success: false
[Container] 2018/10/23 20:40:48 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: node ./test.js. Reason: exit status 1
[Container] 2018/10/23 20:40:48 Entering phase POST_BUILD
[Container] 2018/10/23 20:40:48 Phase complete: POST_BUILD Success: true
[Container] 2018/10/23 20:40:48 Phase context status code:  Message:
```

</p>
</details>

[Click here to retry the build](https://ut2fgw3cae.execute-api.ap-southeast-2.amazonaws.com/development//retry-build?repo=mysqldump&commit=a4480f7b08916657e268d067178275cf6be1d5f8&retryToken=d65c50ed-7d50-4376-b237-5e11e3615624)

2019-03-24 21:55 UTC, bradzacher requested changes
Few things
- revert the changes to the package.json
- remove package-lock.json
- why did you switch the import style for `deepmerge`?

2019-03-24 22:25 UTC, pbassut commented
I should probably polish this up a bit I did this for a company I work for and I thought I would just be a matter of pushing to the fork and be done with it. 
I'll make the necessary changes and push again

2019-09-25 16:23 UTC, ksairi commented
@pbassut is this merge going to be ready soon?
cheers!

2019-12-26 12:05 UTC, closed without merging