keep the table order of the table whitelist
bradzacher/mysqldump pull request #73
Opened 2019-05-29 14:59 UTC by Kosta-Github

When providing a table whitelist the order of that whitelist should be kept when dumping the tables.

This helps if dumping the database without table locks and having tables with foreign key references into other tables. By carefully defining the order of tables you can still achieve a consistent dump without violating the referential integrity by first dumping the table containing the foreign key, followed by the table which is the target of the reference.

2019-05-29 16:42 UTC, bradzacher requested changes
Doesn't this give you a false sense of security unless your table structure is an acyclic graph?
As soon as there are potential cycles in your structure, this method is no safer.

I would probably go as far as to say that using this tool to dump a live production database with no locks should be classified as an unsupported use case because there are so many potential foot-guns.

2019-05-29 16:42 UTC, bradzacher commented on src/getTables.ts
> +                .map(tableName => actualTables.find(t => t.name === tableName)) // keeping the order of the passed-in whitelist
avoid placing the comments at the end of lines

```suggestion
                // keeping the order of the passed-in whitelist
                .map(tableName => actualTables.find(t => t.name === tableName))
```

2019-05-29 16:42 UTC, bradzacher commented on src/getTables.ts
> +                .filter(t => Boolean(t)) as Array<Table>; // filter out non-existing tables
You should avoid using a type cast unless it's _absolutely_ necessary.
Also you should avoid using the `Boolean` constructor because it does too much magic in terms of truthy/falsey coercion.

For `filter`, you can annotate with a type predicate
```suggestion
                // filter out non-existing tables
                .filter((t): t is Table => t != null);
```

2019-05-29 16:51 UTC, Kosta-Github commented
yeah, my use case is for acyclic dependencies for which I can create a correct partial order of the tables, but this would break for true cycles...

my last PR about supporting `table locks` https://github.com/bradzacher/mysqldump/pull/68 doesn't play that nicely with `AWS Aurora` and `read replica`: `SET GLOBAL read_only = ON` is not allowed on them, so I am trying to find other solutions...

maybe you can provide some `pre` & `post` command hooks where someone can feed in some commands required to `lock` and `unlock` the DB accordingly, which might be different for `MySQL` and `AWS Aurora - read replica`, and maybe some other variants?

2019-05-29 17:03 UTC, bradzacher commented
it seems to me like you want to set your master DB to `read_only` before you start your dump?
That or just dump normally, and then clean up the data afterward?

2019-07-19 12:59 UTC, Kosta-Github commented on src/getTables.ts
> +                .filter(t => Boolean(t)) as Array<Table>; // filter out non-existing tables
this will give you the lint error: `Expected '!==' and instead saw '!='  eqeqeq` ...

2019-07-19 13:06 UTC, Kosta-Github commented
What would be the drawback of merging this PR?
It just changes the order of the scanned tables from a not-controllable (random) manner to a controllable-by-the-calling-user order.

2019-07-19 15:19 UTC, merged

2019-07-24 11:36 UTC, Kosta-Github commented
may I ask you for pushing out a new release containing these changes?